export const GLOBALTYPES = {
    AUTH_REQUEST: "AUTH_REQUEST",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    UPDATE_USER_DATA: "UPDATE_USER_DATA",
    AUTH_FAIL: "AUTH_FAIL",
    AUTH_ERROR_MSG: "AUTH_ERROR_MSG",
    SET_FOLLOWING_REQUEST: "SET_FOLLOWING_REQUEST",
    REMOVE_FOLLOWING_REQUEST: "REMOVE_FOLLOWING_REQUEST",
    ADD_FOLLOWING_REQUEST: "ADD_FOLLOWING_REQUEST",
    SET_LOGIN_BTN_STATUS: "SET_LOGIN_BTN_STATUS",
    AUTHREADY_REQUEST: "AUTHREADY_REQUEST",
    AUTHREADY_SUCCESS: "AUTHREADY_SUCCESS",
    AUTHREADY_FAIL: "AUTHREADY_FAIL",
    ALERT_REQUEST: "ALERT_REQUEST",
    ALERT_SUCCESS: "ALERT_SUCCESS",
    ALERT_FAIL: "ALERT_FAIL",
    THEME: 'THEME',
    STATUS: 'STATUS',
    MODAL: 'MODAL',
    PEER: 'PEER',
    REMOVE_USER_REQUEST:'REMOVE_USER_REQUEST',
    REMOVE_USER_SUCCESS:'REMOVE_USER_SUCCESS',
    REMOVE_USER_FAIL:'REMOVE_USER_FAIL',
    GET_FRIENDS_REQUEST:'GET_FRIENDS_REQUEST',
    GET_FRIENDS_SUCCESS:'GET_FRIENDS_SUCCESS',
    GET_FRIENDS_FAIL:'GET_FRIENDS_FAIL',
    DELETE_FRIENDS_REQUEST:"DELETE_FRIENDS_REQUEST",
    DELETE_FRIENDS_SUCCESS:"DELETE_FRIENDS_SUCCESS",
    DELETE_FRIENDS_FAIL:"DELETE_FRIENDS_FAIL",
    VERIFY_DATA_REQUEST:"VERIFY_DATA_REQUEST",
    VERIFY_DATA_SUCCESS:"VERIFY_DATA_SUCCESS",
    VERIFY_DATA_FAIL:"VERIFY_DATA_FAIL",
    CHANGE_PASSWORD_REQUEST:"CHANGE_PASSWORD_REQUEST",
    CHANGE_PASSWORD_SUCCESS:"CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAIL:"CHANGE_PASSWORD_FAIL"
}

export const EditData = (data, id, post) => {
    const newData = data.map(item =>
        (item.id === id ? post : item)
    )
    return newData;
}


export const DeleteData = (data, id) => {
    const newData = data.filter(item => item.id !== id)
    return newData;
}
